version: "3.2"

services:
  web:
    build: .
    ports:
      - "$PORT:$PORT"
    volumes:
      - ./app_api:/app/app_api
      - ./app_client:/app/app_client
      - ./app_lib:/app/app_lib
      - ./bin:/app/bin
      - ./config:/app/config
      - ./doc:/app/doc
      - ./test:/app/test
    depends_on:
      - db
      - adminer
      - redis
      - swift
  
  redis:
    image: "redis:alpine"
    
  db:
    image: "mysql:5.7"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./dev_database:/var/lib/mysql
      
  adminer:
    image: adminer
    restart: always
    ports:
      - "$PORT_DB_ADMIN:8080"
  
  swift:
    image: morrisjobke/docker-swift-onlyone
    restart: always
    volumes:
      - ./dev_container:/srv
    ports:
      - "$PORT_CONTAINER:8080"
