version: "3.2"

services:
  web:
    build: .
    ports:
      - "$PORT:$PORT"
    volumes:
      - ./app_api:/app/app_api
      - ./app_client:/app/app_client
      - ./bin:/app/bin
      - ./public:/app/public
      - ./test:/app/test
    depends_on:
      - db
      - adminer
      - redis
  
  redis:
    image: "redis:alpine"
    
  db:
    image: "mysql:5.5"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./dev_database:/var/lib/mysql
      
  adminer:
    image: adminer
    restart: always
    ports:
      - "$PORT_DB_ADMIN:8080"

      
