FROM node:12

# Create app directory
WORKDIR /app

# Set environment variables
ENV NODE_ENV development
ENV NODE_PATH /app

# install and editor just in case
RUN ["apt-get", "update"]
RUN ["apt-get", "install", "-y", "nano"]

# copy some app starting files
# (app sources will be bound for development)
COPY ./app.js ./
COPY ./*.json ./
COPY ./.env ./

# Install dependencies
RUN ["npm", "install"]
RUN ["npm", "install", "-g", "nodemon@^1.18.8"]

EXPOSE $PORT

CMD ["nodemon"]
