FROM node:12

WORKDIR /app

ENV NODE_ENV production
ENV NODE_PATH /app

COPY ./app.js ./
COPY ./*.json ./
COPY ./.env ./

RUN ["npm", "install", "--only=production"]

EXPOSE $PORT

CMD [ "npm", "start" ]
