version: "3.2"

services:
  web:
    build: .
    container_name: spotair
    restart: always
    expose:
      - 3000
    volumes:
      - ./app_api:/app/app_api
      - ./app_client:/app/app_client
      - ./app_lib:/app/app_lib
      - ./www:/app/www
      - ./passport.config.js:/app/passport.config.js
      - ./doc:/app/doc
      - ./$LOCAL_STORAGE_LOCATION:/app/$LOCAL_STORAGE_LOCATION
    depends_on:
      - db
      - redis
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=https"
      - "traefik.frontend.rule=Host:cloud.spotair.org"
      - "traefik.backend=spotair"
      - "traefik.port=3000"
  
  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always
    
  db:
    image: "mysql:5.7"
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password --event-scheduler=ON
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    volumes:
      - ./dev_database:/var/lib/mysql
      
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    expose:
      - 8080
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=dbadmin"
      - "traefik.frontend.rule=Host:cloud.spotair.org"
      - "traefik.backend=dbAdmin"
      - "traefik.port=8080"
      
  reverse-proxy:
    image: traefik
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "$PORT_DB_ADMIN:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
    environment:
      - OVH_ENDPOINT=ovh-eu
      - OVH_APPLICATION_KEY=$OVH_APPLICATION_KEY
      - OVH_APPLICATION_SECRET=$OVH_APPLICATION_SECRET
      - OVH_CONSUMER_KEY=$OVH_CONSUMER_KEY
